sample_file: /faststorage/project/TCRseq_AZ/Analysis/asbjoern/workflows/TCRseq_testdata/test_sample_file.tsv

mixcr_jar_path: /faststorage/project/TCRseq_AZ/Analysis/asbjoern/tools/mixcr-3.0.13/mixcr.jar

out_path: results
report_path: ""

Sample_ID_colname: Sample_ID_test_gz
R1_colname: TCR_R1_path_test_gz
R2_colname: TCR_R2_path_test_gz
