sample_file: config/mixcr_sample_file.tsv

mixcr_jar_path: /faststorage/project/TCRseq_AZ/Analysis/asbjoern/mixcr-3.0.13/mixcr.jar

out_path: results3
report_path: results3

Sample_ID_colname: Sample_ID_run
R1_colname: TCR_R1_path
R2_colname: TCR_R2_path
